spring:
  datasource:
    url: jdbc:mysql://localhost:3306/my_blog?characterEncoding=utf-8&useSSL=false
    username: root
    password: root123
  security:
    user:
      name: deschen
      password: root123
deschen:
  security:
    browser:
      loginPage: /demo-login.html
    #      loginType: REDIRECT
    code:
      image:
        width: 80
        height: 30
        length: 6
        urls: /authentication/form, /user
